### ISSUE TITLE
geth.ipc can't be created

### ISSUE THREAD

**Issue by minxinping0105** [ethmobile/ethdroid#2]
By using geth1.4 for android, geth.ipc can't be created, and the node file also don't eist.

**Comment by dlecan** [comment]
Can you give more details ?
- Android version
- Smartphone model
- Stacktrace/exception/error log

Thank you

**Comment by minxinping0105** [comment]
Android version is 6.0

Stacktrace/exception/error log as follows:
Connected to process 30877 on device meizu-m5_note-621QECPM2379Y
I/InstantRun: Instant Run Runtime started. Android package is com.sqli.blockchain.ethereum_android_sample, real application class is com.sqli.blockchain.ethereum_android_sample.SampleApplication.
W/art: Suspending all threads took: 21.217ms
I/art: Background sticky concurrent mark sweep GC freed 13990(791KB) AllocSpace objects, 4(96KB) LOS objects, 19% free, 14MB/18MB, paused 22.215ms total 54.664ms
I/System: FinalizerDaemon: finalize objects = 1
I/Stderr: flag provided but not defined: -genesis
I/OpenGLRenderer: Initialized EGL, version 1.4
E/OpenGLRenderer: PerfServiceNative_notifyRenderTime init fail!
I/OpenGLRenderer: Get enable program binary service property (1)
I/OpenGLRenderer: Program binary detail: Binary length is 173456, program map length is 152.
I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 44, and path is /dev/ashmem�.
I/OpenGLRenderer: No need to use file discriptor anymore, close fd(44).
W/libEGL: [ANDROID_RECORDABLE] format: 1
I/[MALI][Gralloc]: [+]r_hnd(0x7f9615a7e0), client(48), share_fd(46)
I/[MALI][Gralloc]: [+]r_hnd(0x7f9615ab00), client(48), share_fd(50)
I/[MALI][Gralloc]: [+]r_hnd(0x7f9615a920), client(48), share_fd(52)

**Comment by minxinping0105** [comment]
We expand some function on ethereum-1.4, and the project can run successfully on ubuntu or windows

**Comment by dlecan** [comment]
There is nothing in your error log related to either ethereum-android or geth.

What are you trying to do ? If you are trying to use our sample, documentation is missing.

With the sample, you have to configure in https://github.com/sqli-nantes/ethereum-android/tree/master/ethereum-android-sample/src/main/assets:
- `genesis.json` which described your private Blockchain
- `static-nodes.json` which described at least one node of your private Blockchain

**Comment by minxinping0105** [comment]
We add some new params on txpool and p2p. But the origin of ethereum 1.4 can run successfully on androud.

**Comment by dlecan** [comment]
> But the origin of ethereum 1.4 can run successfully on androind.

So, what is your problem ?
