### ISSUE TITLE
Ethdroid crashes with OutOfBoundsException

### ISSUE THREAD

**Issue by Nigui** [ethmobile/ethdroid#22]
Ethdroid throws an OutOfBoundsException when creating an instance of Ethdroid with a referenced but empty key manager.

The reason is that, by default Ethdroid's Builder sets as main account the first account of the key manager (if referenced). But it doesn't verify if referenced key manager has accounts.

**Comment by dlecan** [comment]
Beware of abusing of too many nullable objects.
What's the meaning of a null main account?

Is it possible to use an "empty" account or an `Optional<Account>` instead?

Null usage leads to NPE and maintenance nightmare.

**Comment by Nigui** [comment]
The main account is : 
- manually set by the user if he defined a key manager
- automatically set as soon as a key manager has be referenced (first account in the key manager)
- null if no key manager has been referenced in ethdroid or there is an empty one. 

This logic allows the user to do lot of things with few configurations.
