### ISSUE TITLE
How to send ether using ethdroid

### ISSUE THREAD

**Issue by sunnyaditya** [ethmobile/ethdroid#45]
I would like to send ether from 1 account to other account using ethdroid api but I couldn't find api to do it.

Could you please tell me steps for sending ether api flow?

**Comment by Nigui** [comment]
Hey, take a look at our [sample](https://github.com/ethmobile/ethdroid-sample/blob/master/app/src/main/java/io/ethmobile/ethdroidsample/private_chain/PrivateChainActivity.java#L110-L115). 
If you encounter any issues, feel free to create an issue.
