### ISSUE TITLE
Update to Geth 1.6.2 as soon as it is released

### ISSUE THREAD

**Issue by Nigui** [ethmobile/ethdroid#6]
Upgrade to Geth 1.6.2 release, then clean-up snapshot configuration:
https://github.com/ethereum/go-ethereum/releases/tag/v1.6.2

```
allprojects {
    repositories {
        maven { url "https://oss.sonatype.org/content/groups/public" } 
    }
}
```
It's caused by geth version used in Ethdroid (1.6.2) which is a snapshot (so deployed on sonatype repo).

This contrainte must be removed.

**Comment by dlecan** [comment]
So where will come Geth releases from?
